

create database "raj"

CREATE TABLE EMP (
EMP_ID INT,
EMP_NAME VARCHAR(30),
EMP_LOCATION VARCHAR(30),
EMP_SALARY INT
)

INSERT INTO EMP VALUES (5,'vijay','BANGLORE',10000)

SELECT * FROM EMP

CREATE TABLE ORDERS(
CUSTOMER_ID INT,
ORDER_ID INT,
CUSTOMER_NAME VARCHAR(30),
CUSTOMER_LOCATION VARCHAR(30),
ORDER_DATE DATETIME
)

INSERT INTO ORDERS VALUES (2,1003,'RAM','BANGLORE','2023-11-30 03:32:15')

SELECT * FROM ORDERS WHERE ORDER_DATE > '2023-11-30 01:32:15'

SELECT max(ORDER_DATE) MAXDATE FROM ORDERS